Have at least three sites in each state
palewire/news-homepages pull request #347
Opened 2022-12-03 20:19 UTC by stucka

as in 343 and 346

2022-12-03 21:07 UTC, palewire requested changes

2022-12-03 21:07 UTC, palewire commented on newshomepages/sources/sites.csv
> +_fiquemsabendo,https://fiquemsabendo.substack.com/,Fiquem Sabendo,Sao Paulo,America/Sao_Paulo,BR,pt,,
We cut the leading `_` on this solve an archive.org bug. Can you catch up with the tweak in main?

2022-12-03 21:07 UTC, palewire commented
Are you sure all of the bundles you're adding are in the bundles.csv file?

2022-12-03 21:36 UTC, stucka commented
Leading underscore fixed. All sites' bundles verified. I'll Slack you my lil helper script.

2022-12-03 22:16 UTC, palewire requested changes

2022-12-03 22:16 UTC, palewire commented on newshomepages/sources/sites.csv
> -verge,https://www.theverge.com/,Verge,New York City,America/New_York,US,en,tech,
Did we lose The Verge?

2022-12-03 22:16 UTC, palewire commented
Gotcha. Verge thing is my only remaining question.

2022-12-05 15:02 UTC, stucka reviewed
Bring back verge

2022-12-05 15:28 UTC, merged

2022-12-05 15:28 UTC, palewire commented
Thank you!